version: '3'

services:
    database:
        image: mysql:5.7
        volumes:
            - ./vote-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: asd123
            MYSQL_DATABASE: votedb
            MYSQL_USER: voteuser
            MYSQL_PASSWORD: pass123
        networks:
            - votenet

    application:
        environment:
            DB_HOST: database
            DB_PORT: 3306
            DB_NAME: votedb
            DB_USER: voteuser
            DB_PASS: pass123
            DB_TYPE: mysql
        restart: on-failure
        depends_on:
            - database
        build: ./build
        volumes:
            - ./vote-app:/app
        ports:
            - 80:5000
        networks:
            - votenet

networks:
    votenet:
